version: "3"
services:
  db:
    image: postgres:11.5
    command: postgres -c log_statement=all
    ports:
      - 5432:5432
  veneer:
    container_name: transmission
    build:
      context: .
    command: bash -c "rm -f ./tmp/pids/server.pid && tail -f /dev/null"
    volumes:
      - ${PWD}:/usr/src/app
    depends_on:
      - db
    ports:
      - 5552:5552